# fly.toml app configuration file for prisoners-dilemma-bot (free tier optimized)

app = "prisoners-dilemma-bot"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true        # auto stop when idle
  auto_start_machines = true       # auto start on request
  min_machines_running = 0         # to save resources when idle
  processes = ["app"]

[[vm]]
  memory = "256mb"                 # fits free plan (do NOT set memory_mb as well)
  cpu_kind = "shared"
  cpus = 1
